### ISSUE TITLE
Invalid syntax on passivbot.py

### ISSUE THREAD

**Issue by eugjr** [enarjord/passivbot_binance_isolated_margin_legacy#1]
Hello, I'm trying to running your bot with a test account, and stumbled on the following error:

Running with Python 3.7 the following error appears:
  File "passivbot.py", line 31
    if (s:= f"{c}/{settings['quot']}") in all_margin_pairs]
         ^
Syntax Error: Invalid Syntax

Running with Python 3.8, the following:
  File "passivbot.py", line 31
    if (s:= f"{c}/{settings['quot']}") in all_margin_pairs]
SyntaxError: closing parenthesis ')' does not match opening parnteshis '['

I"ve setup the key on the .json file, named as "user".
Thanks

**Comment by enarjord** [comment]
hello eugjr,

thanks for commenting

python <= 3.7 will not work

i just tried with python 3.8 and it works fine. i was unable to reproduce your error.

are you on windows, mac or linux?

you are sure you are running with python3.8?

what's the output of
`python3.8 --version`

**Comment by eugjr** [comment]
Hi, thanks for answering it. I'm on windows 7
on cmd the command python3.8 --version result in:
Python 3.8.0

I'm doing a reinstall of the required components (ccxp, python-binance, etc.). I'm unable to complete the instalation of ciso8061 component,.

**Comment by enarjord** [comment]
I just updated the bot, it no longer requires ciso8601

clone the repo anew and try again

let me know if the bug persists

**Comment by eugjr** [comment]
Thank you so much, bypassed the error. 
I'll test it and contact you after.
