### ISSUE TITLE
Repaying issue

### ISSUE THREAD

**Issue by netasolutions** [enarjord/passivbot_binance_isolated_margin_legacy#4]
Hi,
If balance is not enough to repay all debt of an altcoin it stucks there and waits for available balance. 
maybe we should think of repaying partially? 

ERROR margin ADA/BTC create_margin_bid insufficient funds; schedule balance update

**Comment by netasolutions** [comment]
Bot still continues to work but on that alt coin it always try to bid whole debt amount and couldnt execute because of insufficient funds.

**Comment by enarjord** [comment]
hello, thanks for commenting

does it get the insufficient funds error continuously, or sporadically once in a while?

i've looked it over, it should be doing partial repays...

some issues were fixed a couple of days ago, are you running latest version?

**Comment by netasolutions** [comment]
Hello, thanks for fast response. 
I pulled last changes few hours ago it happened 1-2 times after pulling the last changes. 
I will monitor carefully. Also i am planning to create a dashboard to check logs and trades more detailed. 
maybe i will start next week. I will send you repo url for the dashboard if i have enough time to develop. 
by the way it seems really nice strategy. I want to help to improve more.

**Comment by enarjord** [comment]
thank you, appreciated

sometimes the bot will get an insufficient funds error because an order was just taken, but local balance is not updated yet. that is normal
